name: Battlegrounds
author: nahkd123
version: 1.0.0-1.15.2
main: me.nahkd.spigot.btg.Battlegrounds
softdepend: [ErotoLib]
api-version: 1.15

commands:
  bgadmin:
    description: "Admin command. /bgadmin wizard to setup arena"
    usage: "/bgadmin [wizard|cheat <id [skinname]>|list]"
    permission: "battlegrounds.admin"
    
permissions:
  battlegrounds.admin:
    description: "Administrator's permission. Already served to OPs"
    default: op