name: Battlegrounds
author: nahkd123
version: 1.0.1-1.15.2
main: me.nahkd.spigot.btg.Battlegrounds
api-version: 1.15

commands:
  bgadmin:
    description: "Admin command. /bgadmin wizard to setup arena"
    usage: "/bgadmin [wizard|cheat <id [skinname]>|list]"
    permission: "battlegrounds.admin"
  bg:
    description: "View plugin information"
    aliases: [battleground, battlegrounds, bginfo]
    usage: "/bg"
    permission: "battleground.info"
    
permissions:
  battlegrounds.admin:
    description: "Administrator's permission. Already served to OPs"
    default: op
  battleground.info:
    description: "Allow to view plugin information"
    default: true